title: Intermediate App Inventor Sushi Cards
hero_image: images/banner.png
description: Make an app that tracks how much exercise you do
version: 1
listed: false
copyedit: false
last_tested: "2018-04-30"
steps:
  - title: Introduction
  - title: What you will need
  - title: Recording exercise
  - title: Calculating the total
  - title: Saving the information
  - title: Resetting
  - title: Record a message!
  - title: Displaying the exercise history
